// Single source of truth for a preset's session length: the stored
// durationSeconds, or — for presets saved before that field existed — the end
// of the last cue rounded up to a whole minute (minimum 60s).
export function presetDurationSeconds(preset) {
  if (typeof preset?.durationSeconds === 'number') return preset.durationSeconds;
  const lastCueEnd = (preset?.cues ?? []).reduce(
    (max, cue) => Math.max(max, cue.time + (cue.duration ?? 0)),
    0
  );
  return Math.max(60, Math.ceil(lastCueEnd / 60) * 60);
}

// Default presets are app content (translated by id); user presets show their
// literal name. t echoes the key back on miss, which is how we detect a user preset.
export function resolvePresetName(preset, t) {
  const key = `presets.${preset.id}`;
  const translated = t(key);
  return translated === key ? preset.name : translated;
}

// Semantic colour language for cue clips: a cue's colour encodes its role in
// the session, so the timeline reads at a glance across every preset.
export const CUE_COLORS = {
  opening: '#f6a133',    // the bell that starts the session
  closing: '#b886d0',    // the bell, bowl or gong that ends it
  transition: '#c97761', // return and section-warning markers
  guidance: '#a0c4e8',   // breath and spoken-guidance fx
  earth: '#9bb56f',      // forest and earth ambient beds
  water: '#6fa7c4',      // water and wind ambient beds
  tonal: '#e0c46f',      // chimes, crystal and gentle tones, flute
};

export const DEFAULT_PRESETS = [
  {
    id: 'default-yoga-nidra',
    name: 'Yoga Nidra',
    createdAt: '2026-06-07T00:00:00.000Z',
    durationSeconds: 1800,
    cues: [
      {
        id: 'yn-start',
        name: 'Inicio',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.opening,
        sound: 'bells/singing-bell.mp3',
        time: 0,
        duration: 25,
        volume: 72,
        fadeIn: 1,
        fadeOut: 10,
        instruction: 'Acuéstate. Ojos cerrados. No te muevas',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'yn-ocean',
        name: 'Océano',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/ocean-gentle.mp3',
        time: 60,
        duration: 1500,
        volume: 36,
        fadeIn: 30,
        fadeOut: 40,
        instruction: 'Escucha el sonido. No hagas nada',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'yn-breath',
        name: 'Respiración',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/breath-cue.mp3',
        time: 180,
        duration: 20,
        volume: 55,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Observa el aire que entra y sale',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'yn-scan1',
        name: 'Cuerpo superior',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.tonal,
        sound: 'fx/gentle-tone.mp3',
        time: 360,
        duration: 15,
        volume: 52,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Mano derecha · brazo · hombro · cuello',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'yn-scan2',
        name: 'Torso',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.tonal,
        sound: 'fx/gentle-tone.mp3',
        time: 600,
        duration: 15,
        volume: 52,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Pecho · abdomen · espalda · cadera',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'yn-scan3',
        name: 'Cuerpo inferior',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.tonal,
        sound: 'fx/gentle-tone.mp3',
        time: 840,
        duration: 15,
        volume: 52,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Pierna derecha · izquierda · pies',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'yn-opposites',
        name: 'Pares opuestos',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.earth,
        sound: 'fx/crystal-tone.mp3',
        time: 1020,
        duration: 20,
        volume: 50,
        fadeIn: 3,
        fadeOut: 6,
        instruction: 'Frío · calor · pesado · ligero · dolor · placer',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'yn-visual',
        name: 'Visualización',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.closing,
        sound: 'fx/flute-peaceful.mp3',
        time: 1260,
        duration: 35,
        volume: 48,
        fadeIn: 6,
        fadeOut: 10,
        instruction: 'Un lago tranquilo al amanecer',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'yn-return',
        name: 'Retorno',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.transition,
        sound: 'bells/chime-meditation.mp3',
        time: 1500,
        duration: 20,
        volume: 62,
        fadeIn: 2,
        fadeOut: 8,
        instruction: 'Vuelve a sentir tu cuerpo completo',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'yn-wake',
        name: 'Despertar',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.opening,
        sound: 'bells/meditation-bell-classic.mp3',
        time: 1680,
        duration: 22,
        volume: 70,
        fadeIn: 1,
        fadeOut: 8,
        instruction: 'Mueve los dedos. Respira profundo',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'yn-end',
        name: 'Cierre',
        kind: 'bowl',
        icon: 'bowl',
        color: CUE_COLORS.closing,
        sound: 'bells/tibetan-bowl-resonant.mp3',
        time: 1710,
        duration: 90,
        volume: 80,
        fadeIn: 8,
        fadeOut: 22,
        instruction: '',
        instructionDuration: 5,
        notes: '',
      },
    ],
  },
  {
    id: 'default-pranayama-478',
    name: 'Pranayama 4-7-8',
    createdAt: '2026-06-07T00:00:00.000Z',
    durationSeconds: 900,
    cues: [
      {
        id: 'pr478-start',
        name: 'Inicio',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.opening,
        sound: 'bells/japanese-temple-bell.mp3',
        time: 0,
        duration: 20,
        volume: 76,
        fadeIn: 1,
        fadeOut: 6,
        instruction: 'Inhala 4 · Retén 7 · Exhala 8',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'pr478-r1',
        name: 'Ronda 1',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/breath-cue.mp3',
        time: 120,
        duration: 30,
        volume: 60,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Inhala 4 · Retén 7 · Exhala 8',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'pr478-rest1',
        name: 'Descanso',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/river-gentle.mp3',
        time: 300,
        duration: 60,
        volume: 42,
        fadeIn: 10,
        fadeOut: 10,
        instruction: 'Respira normal. Descansa',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'pr478-r2',
        name: 'Ronda 2',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/breath-cue.mp3',
        time: 360,
        duration: 30,
        volume: 60,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Reanuda: Inhala 4 · Retén 7 · Exhala 8',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'pr478-mid',
        name: 'Mitad',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.tonal,
        sound: 'fx/chimes-light.mp3',
        time: 450,
        duration: 15,
        volume: 58,
        fadeIn: 1,
        fadeOut: 4,
        instruction: 'Mitad de práctica',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'pr478-r3',
        name: 'Ronda 3',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/breath-cue.mp3',
        time: 600,
        duration: 30,
        volume: 60,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Última ronda',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'pr478-end',
        name: 'Cierre',
        kind: 'bowl',
        icon: 'bowl',
        color: CUE_COLORS.closing,
        sound: 'bells/tibetan-bowl-pure.mp3',
        time: 840,
        duration: 30,
        volume: 78,
        fadeIn: 3,
        fadeOut: 12,
        instruction: 'Completa. Respira natural',
        instructionDuration: 7,
        notes: '',
      },
    ],
  },
  {
    id: 'default-meditacion-matutina',
    name: 'Meditacion matutina',
    createdAt: '2026-06-07T00:00:00.000Z',
    durationSeconds: 1200,
    cues: [
      {
        id: 'mm-start',
        name: 'Inicio',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.opening,
        sound: 'bells/meditation-bell.mp3',
        time: 0,
        duration: 18,
        volume: 76,
        fadeIn: 1,
        fadeOut: 7,
        instruction: 'Siéntate. Cierra los ojos',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'mm-ambient',
        name: 'Bosque',
        kind: 'ambient',
        icon: 'forest',
        color: CUE_COLORS.earth,
        sound: 'ambient/forest-day.mp3',
        time: 60,
        duration: 600,
        volume: 46,
        fadeIn: 20,
        fadeOut: 25,
        instruction: 'Observa tu respiración',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'mm-mid',
        name: 'Mitad',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.tonal,
        sound: 'bells/chime-meditation.mp3',
        time: 600,
        duration: 20,
        volume: 62,
        fadeIn: 1,
        fadeOut: 6,
        instruction: 'Mitad de la práctica',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'mm-final5',
        name: 'Últimos 5 min',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.transition,
        sound: 'fx/chimes-medium.mp3',
        time: 900,
        duration: 18,
        volume: 60,
        fadeIn: 1,
        fadeOut: 5,
        instruction: 'Últimos 5 minutos',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'mm-return',
        name: 'Vuelve',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.closing,
        sound: 'bells/crystal-bowl-medium.mp3',
        time: 1140,
        duration: 25,
        volume: 70,
        fadeIn: 2,
        fadeOut: 10,
        instruction: 'Prepárate para volver',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'mm-end',
        name: 'Cierre',
        kind: 'bowl',
        icon: 'bowl',
        color: CUE_COLORS.closing,
        sound: 'bells/tibetan-bowl-resonant.mp3',
        time: 1170,
        duration: 30,
        volume: 82,
        fadeIn: 8,
        fadeOut: 20,
        instruction: 'Abre los ojos cuando quieras',
        instructionDuration: 7,
        notes: '',
      },
    ],
  },
  {
    id: 'default-relajacion-profunda',
    name: 'Relajacion profunda',
    createdAt: '2026-06-07T00:00:00.000Z',
    durationSeconds: 1800,
    cues: [
      {
        id: 'rp-start',
        name: 'Inicio',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.opening,
        sound: 'bells/singing-bell.mp3',
        time: 0,
        duration: 22,
        volume: 72,
        fadeIn: 1,
        fadeOut: 8,
        instruction: 'Acuéstate. Cierra los ojos',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'rp-ocean',
        name: 'Océano',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/ocean-gentle.mp3',
        time: 120,
        duration: 900,
        volume: 44,
        fadeIn: 25,
        fadeOut: 30,
        instruction: 'Deja que el cuerpo se hunda',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'rp-relax1',
        name: 'Suelta',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.tonal,
        sound: 'fx/flute-peaceful.mp3',
        time: 600,
        duration: 40,
        volume: 55,
        fadeIn: 5,
        fadeOut: 10,
        instruction: 'Relaja mandíbula, cuello, hombros',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'rp-deep',
        name: 'Profundo',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.earth,
        sound: 'fx/crystal-tone.mp3',
        time: 1080,
        duration: 30,
        volume: 58,
        fadeIn: 3,
        fadeOut: 8,
        instruction: 'Más profundo',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'rp-return',
        name: 'Vuelve',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.transition,
        sound: 'fx/water-drop.mp3',
        time: 1500,
        duration: 12,
        volume: 64,
        fadeIn: 1,
        fadeOut: 3,
        instruction: 'Empieza a volver',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'rp-wake',
        name: 'Despierta',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.closing,
        sound: 'bells/meditation-bell-classic.mp3',
        time: 1740,
        duration: 22,
        volume: 74,
        fadeIn: 1,
        fadeOut: 8,
        instruction: 'Mueve los dedos. Abre los ojos',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'rp-end',
        name: 'Cierre',
        kind: 'gong',
        icon: 'gong',
        color: CUE_COLORS.closing,
        sound: 'bells/zen-gong.mp3',
        time: 1765,
        duration: 35,
        volume: 80,
        fadeIn: 4,
        fadeOut: 22,
        instruction: '',
        instructionDuration: 5,
        notes: '',
      },
    ],
  },
  {
    id: 'default-caminata-consciente',
    name: 'Caminata consciente',
    createdAt: '2026-06-07T00:00:00.000Z',
    durationSeconds: 600,
    cues: [
      {
        id: 'cc-start',
        name: 'Comienza',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.earth,
        sound: 'fx/bird-chirp-multiple.mp3',
        time: 0,
        duration: 12,
        volume: 70,
        fadeIn: 1,
        fadeOut: 3,
        instruction: 'Empieza a caminar despacio',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'cc-paso',
        name: 'Pasos',
        kind: 'ambient',
        icon: 'forest',
        color: CUE_COLORS.earth,
        sound: 'ambient/crickets-gentle.mp3',
        time: 120,
        duration: 180,
        volume: 40,
        fadeIn: 12,
        fadeOut: 12,
        instruction: 'Siente cada paso',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'cc-escucha',
        name: 'Escucha',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.tonal,
        sound: 'fx/chimes-small.mp3',
        time: 240,
        duration: 14,
        volume: 62,
        fadeIn: 1,
        fadeOut: 4,
        instruction: '¿Qué escuchas?',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'cc-cuerpo',
        name: 'Cuerpo',
        kind: 'ambient',
        icon: 'forest',
        color: CUE_COLORS.water,
        sound: 'ambient/wind-gentle.mp3',
        time: 360,
        duration: 120,
        volume: 38,
        fadeIn: 10,
        fadeOut: 10,
        instruction: '¿Qué sientes en el cuerpo?',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'cc-ritmo',
        name: 'Ritmo',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.earth,
        sound: 'fx/bird-chirp-multiple.mp3',
        time: 480,
        duration: 12,
        volume: 65,
        fadeIn: 1,
        fadeOut: 3,
        instruction: 'Vuelve al ritmo del paso',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'cc-end',
        name: 'Detente',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.closing,
        sound: 'bells/gong-bell.mp3',
        time: 570,
        duration: 25,
        volume: 74,
        fadeIn: 2,
        fadeOut: 10,
        instruction: 'Detente. Respira',
        instructionDuration: 7,
        notes: '',
      },
    ],
  },
  {
    id: 'default-bosque-nocturno',
    name: 'Bosque nocturno',
    createdAt: '2026-08-29T00:00:00.000Z',
    durationSeconds: 2100,
    cues: [
      {
        id: 'bn-start',
        name: 'Entrada',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.opening,
        sound: 'bells/singing-bell.mp3',
        time: 0,
        duration: 25,
        volume: 62,
        fadeIn: 1,
        fadeOut: 10,
        instruction: 'Acuestate. Deja que la noche empiece',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'bn-forest',
        name: 'Bosque',
        kind: 'ambient',
        icon: 'forest',
        color: CUE_COLORS.earth,
        sound: 'ambient/forest-night.mp3',
        time: 45,
        duration: 700,
        volume: 40,
        fadeIn: 40,
        fadeOut: 60,
        instruction: 'No escuchas un sonido: escuchas un lugar',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'bn-crickets',
        name: 'Grillos',
        kind: 'ambient',
        icon: 'forest',
        color: CUE_COLORS.earth,
        sound: 'ambient/crickets-summer-night.mp3',
        time: 180,
        duration: 520,
        volume: 28,
        fadeIn: 30,
        fadeOut: 40,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'bn-owl',
        name: 'Buho',
        kind: 'ambient',
        icon: 'forest',
        color: CUE_COLORS.earth,
        sound: 'ambient/owl-distant.mp3',
        time: 300,
        duration: 180,
        volume: 22,
        fadeIn: 10,
        fadeOut: 20,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'bn-rain',
        name: 'Lluvia en la ventana',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/rain-window.mp3',
        time: 690,
        duration: 640,
        volume: 34,
        fadeIn: 55,
        fadeOut: 60,
        instruction: 'Ha empezado a llover. No hagas nada',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'bn-dawn',
        name: 'Amanece',
        kind: 'ambient',
        icon: 'forest',
        color: CUE_COLORS.earth,
        sound: 'ambient/forest-day.mp3',
        time: 1280,
        duration: 700,
        volume: 32,
        fadeIn: 60,
        fadeOut: 80,
        instruction: 'Amanece. El bosque se despierta antes que tu',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'bn-chime',
        name: 'Primera luz',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.tonal,
        sound: 'fx/chimes-light.mp3',
        time: 1900,
        duration: 30,
        volume: 44,
        fadeIn: 5,
        fadeOut: 15,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'bn-end',
        name: 'Cierre',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.closing,
        sound: 'bells/meditation-bell.mp3',
        time: 2050,
        duration: 50,
        volume: 55,
        fadeIn: 3,
        fadeOut: 25,
        instruction: 'Quedate quieto un momento mas',
        instructionDuration: 8,
        notes: '',
      },
    ],
  },
  {
    id: 'default-escaneo-corporal-guiar',
    name: 'Escaneo corporal (guiar)',
    createdAt: '2026-08-29T00:00:00.000Z',
    durationSeconds: 1320,
    cues: [
      {
        id: 'ec-start',
        name: 'Apertura',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.opening,
        sound: 'bells/tibetan-bowl-pure.mp3',
        time: 0,
        duration: 20,
        volume: 60,
        fadeIn: 1,
        fadeOut: 8,
        instruction: 'Acuestate. Brazos separados del cuerpo',
        instructionDuration: 8,
        notes: 'Espera a que el grupo se acomode antes de dar la primera indicacion.',
      },
      {
        id: 'ec-bed',
        name: 'Fondo',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/wind-peaceful.mp3',
        time: 40,
        duration: 1200,
        volume: 20,
        fadeIn: 35,
        fadeOut: 60,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'ec-cabeza',
        name: 'Cabeza',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/gentle-tone.mp3',
        time: 120,
        duration: 15,
        volume: 42,
        fadeIn: 2,
        fadeOut: 6,
        instruction: 'Corona, frente, sienes',
        instructionDuration: 10,
        notes: 'Marca el inicio del recorrido. Voz baja, sin prisa. Deja 20 s de silencio despues.',
      },
      {
        id: 'ec-cara',
        name: 'Cara y cuello',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/gentle-tone.mp3',
        time: 240,
        duration: 15,
        volume: 42,
        fadeIn: 2,
        fadeOut: 6,
        instruction: 'Mandibula, lengua, garganta',
        instructionDuration: 10,
        notes: 'Aqui suele aparecer tension. Invita a soltar la mandibula dos veces.',
      },
      {
        id: 'ec-brazos',
        name: 'Brazos',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/gentle-tone.mp3',
        time: 360,
        duration: 15,
        volume: 42,
        fadeIn: 2,
        fadeOut: 6,
        instruction: 'Hombros, brazos, manos, dedos',
        instructionDuration: 10,
        notes: 'Nombra los dos lados por separado. Derecha primero, luego izquierda.',
      },
      {
        id: 'ec-torso',
        name: 'Torso',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/gentle-tone.mp3',
        time: 480,
        duration: 15,
        volume: 42,
        fadeIn: 2,
        fadeOut: 6,
        instruction: 'Pecho, costillas, espalda',
        instructionDuration: 10,
        notes: 'Vincula con la respiracion: el pecho ya se mueve solo, no hay que hacer nada.',
      },
      {
        id: 'ec-caderas',
        name: 'Caderas',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/gentle-tone.mp3',
        time: 600,
        duration: 15,
        volume: 42,
        fadeIn: 2,
        fadeOut: 6,
        instruction: 'Abdomen, caderas, pelvis',
        instructionDuration: 10,
        notes: 'Zona de peso. Sugiere que se hunda hacia el suelo.',
      },
      {
        id: 'ec-piernas',
        name: 'Piernas',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/gentle-tone.mp3',
        time: 720,
        duration: 15,
        volume: 42,
        fadeIn: 2,
        fadeOut: 6,
        instruction: 'Muslos, rodillas, pantorrillas',
        instructionDuration: 10,
        notes: 'Recorrido largo. No aceleres aunque parezca que sobra tiempo.',
      },
      {
        id: 'ec-pies',
        name: 'Pies',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/gentle-tone.mp3',
        time: 840,
        duration: 15,
        volume: 42,
        fadeIn: 2,
        fadeOut: 6,
        instruction: 'Tobillos, pies, dedos',
        instructionDuration: 10,
        notes: 'Final del recorrido descendente. Silencio largo despues de esta.',
      },
      {
        id: 'ec-todo',
        name: 'Cuerpo entero',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/gentle-tone.mp3',
        time: 960,
        duration: 15,
        volume: 42,
        fadeIn: 2,
        fadeOut: 6,
        instruction: 'Todo el cuerpo a la vez',
        instructionDuration: 10,
        notes: 'Cambia el registro: ya no se recorre, se sostiene entero.',
      },
      {
        id: 'ec-silencio',
        name: 'Silencio',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/gentle-tone.mp3',
        time: 1080,
        duration: 15,
        volume: 42,
        fadeIn: 2,
        fadeOut: 6,
        instruction: 'Ya no hay nada que recorrer',
        instructionDuration: 10,
        notes: 'Ultima indicacion. A partir de aqui no hables hasta el cuenco final.',
      },
      {
        id: 'ec-end',
        name: 'Cuenco final',
        kind: 'bowl',
        icon: 'bowl',
        color: CUE_COLORS.closing,
        sound: 'bells/chakra-bowl.mp3',
        time: 1240,
        duration: 80,
        volume: 56,
        fadeIn: 5,
        fadeOut: 40,
        instruction: 'Vuelve cuando quieras. Sin prisa',
        instructionDuration: 10,
        notes: 'Deja que el cuenco se apague del todo antes de hablar.',
      },
    ],
  },
  {
    id: 'default-foco-trabajo-profundo',
    name: 'Foco profundo',
    createdAt: '2026-08-29T00:00:00.000Z',
    durationSeconds: 3000,
    cues: [
      {
        id: 'ft-start',
        name: 'Empieza',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.opening,
        sound: 'bells/meditation-bell-classic.mp3',
        time: 0,
        duration: 18,
        volume: 46,
        fadeIn: 1,
        fadeOut: 8,
        instruction: 'Una sola tarea. Cierra lo demas',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'ft-bed',
        name: 'Fondo de lluvia',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/rain-window.mp3',
        time: 30,
        duration: 2850,
        volume: 14,
        fadeIn: 60,
        fadeOut: 90,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'ft-mark',
        name: 'Mitad',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.transition,
        sound: 'fx/bamboo-click.mp3',
        time: 1500,
        duration: 8,
        volume: 36,
        fadeIn: 0,
        fadeOut: 3,
        instruction: 'Mitad. No cambies de tarea',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'ft-warn',
        name: 'Ultimos cinco',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.transition,
        sound: 'fx/chimes-small.mp3',
        time: 2700,
        duration: 12,
        volume: 40,
        fadeIn: 1,
        fadeOut: 5,
        instruction: 'Cinco minutos. Empieza a cerrar',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'ft-end',
        name: 'Fin',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.closing,
        sound: 'bells/gong-bell.mp3',
        time: 2940,
        duration: 60,
        volume: 50,
        fadeIn: 3,
        fadeOut: 30,
        instruction: 'Para. Levantate antes de revisar nada',
        instructionDuration: 9,
        notes: '',
      },
    ],
  },
  {
    id: 'default-reset-5-min',
    name: 'Reset de 5 minutos',
    createdAt: '2026-08-29T00:00:00.000Z',
    durationSeconds: 300,
    cues: [
      {
        id: 'rs-start',
        name: 'Empieza',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.opening,
        sound: 'bells/meditation-bell.mp3',
        time: 0,
        duration: 12,
        volume: 56,
        fadeIn: 1,
        fadeOut: 5,
        instruction: 'Sientate recto. Cinco minutos',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'rs-bed',
        name: 'Fondo',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/wind-gentle.mp3',
        time: 15,
        duration: 250,
        volume: 16,
        fadeIn: 15,
        fadeOut: 30,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'rs-b1',
        name: 'Ronda 1',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/breath-cue.mp3',
        time: 30,
        duration: 16,
        volume: 48,
        fadeIn: 1,
        fadeOut: 4,
        instruction: 'Inhala 4 · Reten 4 · Exhala 4 · Reten 4',
        instructionDuration: 12,
        notes: '',
      },
      {
        id: 'rs-b2',
        name: 'Ronda 2',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/breath-cue.mp3',
        time: 90,
        duration: 16,
        volume: 48,
        fadeIn: 1,
        fadeOut: 4,
        instruction: 'Otra vez. Mismo ritmo',
        instructionDuration: 10,
        notes: '',
      },
      {
        id: 'rs-b3',
        name: 'Ronda 3',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/breath-cue.mp3',
        time: 150,
        duration: 16,
        volume: 48,
        fadeIn: 1,
        fadeOut: 4,
        instruction: 'Tercera. Los hombros abajo',
        instructionDuration: 10,
        notes: '',
      },
      {
        id: 'rs-b4',
        name: 'Ronda 4',
        kind: 'fx',
        icon: 'breath',
        color: CUE_COLORS.guidance,
        sound: 'fx/breath-cue.mp3',
        time: 210,
        duration: 16,
        volume: 48,
        fadeIn: 1,
        fadeOut: 4,
        instruction: 'Ultima ronda',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'rs-end',
        name: 'Cierre',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.closing,
        sound: 'bells/chime-meditation.mp3',
        time: 270,
        duration: 30,
        volume: 46,
        fadeIn: 2,
        fadeOut: 18,
        instruction: 'Ya esta. Vuelve a lo que estabas',
        instructionDuration: 9,
        notes: '',
      },
    ],
  },
  {
    id: 'default-bano-de-cuencos',
    name: 'Bano de cuencos',
    createdAt: '2026-08-29T00:00:00.000Z',
    durationSeconds: 1680,
    cues: [
      {
        id: 'bc-open',
        name: 'Golpe inicial',
        kind: 'bowl',
        icon: 'bowl',
        color: CUE_COLORS.opening,
        sound: 'bells/tibetan-bowl-struck.mp3',
        time: 0,
        duration: 40,
        volume: 66,
        fadeIn: 1,
        fadeOut: 20,
        instruction: 'Acuestate. Deja que el sonido te alcance',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'bc-bed',
        name: 'Sala',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/cathedral-ambience.mp3',
        time: 20,
        duration: 1500,
        volume: 18,
        fadeIn: 45,
        fadeOut: 90,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'bc-r1',
        name: 'Cuenco de cristal',
        kind: 'bowl',
        icon: 'bowl',
        color: CUE_COLORS.tonal,
        sound: 'bells/crystal-bowl-large.mp3',
        time: 120,
        duration: 180,
        volume: 50,
        fadeIn: 10,
        fadeOut: 60,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'bc-r2',
        name: 'Chakra',
        kind: 'bowl',
        icon: 'bowl',
        color: CUE_COLORS.tonal,
        sound: 'bells/chakra-bowl.mp3',
        time: 260,
        duration: 200,
        volume: 48,
        fadeIn: 15,
        fadeOut: 70,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'bc-r3',
        name: 'Cuenco tibetano',
        kind: 'bowl',
        icon: 'bowl',
        color: CUE_COLORS.tonal,
        sound: 'bells/tibetan-bowl-resonant.mp3',
        time: 420,
        duration: 220,
        volume: 52,
        fadeIn: 20,
        fadeOut: 80,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'bc-r4',
        name: 'Gong zen',
        kind: 'gong',
        icon: 'gong',
        color: CUE_COLORS.tonal,
        sound: 'bells/zen-gong.mp3',
        time: 600,
        duration: 240,
        volume: 54,
        fadeIn: 20,
        fadeOut: 90,
        instruction: 'No sigas el sonido. Dejalo pasar',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'bc-r5',
        name: 'Cristal medio',
        kind: 'bowl',
        icon: 'bowl',
        color: CUE_COLORS.tonal,
        sound: 'bells/crystal-bowl-medium.mp3',
        time: 800,
        duration: 200,
        volume: 46,
        fadeIn: 20,
        fadeOut: 80,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'bc-r6',
        name: 'Gong profundo',
        kind: 'gong',
        icon: 'gong',
        color: CUE_COLORS.tonal,
        sound: 'bells/gong-deep.mp3',
        time: 1000,
        duration: 260,
        volume: 56,
        fadeIn: 25,
        fadeOut: 100,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'bc-r7',
        name: 'Cuenco puro',
        kind: 'bowl',
        icon: 'bowl',
        color: CUE_COLORS.tonal,
        sound: 'bells/tibetan-bowl-pure.mp3',
        time: 1240,
        duration: 220,
        volume: 48,
        fadeIn: 20,
        fadeOut: 90,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'bc-end',
        name: 'Ultimo gong',
        kind: 'gong',
        icon: 'gong',
        color: CUE_COLORS.closing,
        sound: 'bells/zen-gong.mp3',
        time: 1560,
        duration: 120,
        volume: 58,
        fadeIn: 5,
        fadeOut: 60,
        instruction: 'Espera a que se apague del todo',
        instructionDuration: 10,
        notes: '',
      },
    ],
  },
  {
    id: 'default-tormenta-que-pasa',
    name: 'Tormenta que pasa',
    createdAt: '2026-08-29T00:00:00.000Z',
    durationSeconds: 1440,
    cues: [
      {
        id: 'tp-start',
        name: 'Entrada',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.opening,
        sound: 'bells/japanese-temple-bell.mp3',
        time: 0,
        duration: 22,
        volume: 56,
        fadeIn: 1,
        fadeOut: 10,
        instruction: 'Va a llover. No tienes que hacer nada',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'tp-rain1',
        name: 'Primeras gotas',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/rain-window.mp3',
        time: 30,
        duration: 420,
        volume: 26,
        fadeIn: 40,
        fadeOut: 70,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'tp-build',
        name: 'Se acerca',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/rain-distant-thunder.mp3',
        time: 390,
        duration: 360,
        volume: 34,
        fadeIn: 60,
        fadeOut: 60,
        instruction: 'Se acerca. Sigue quieto',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'tp-peak',
        name: 'Tormenta',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/rain-thunder-long.mp3',
        time: 700,
        duration: 380,
        volume: 44,
        fadeIn: 55,
        fadeOut: 80,
        instruction: 'Encima de ti. Ni te tapes ni la mires',
        instructionDuration: 10,
        notes: '',
      },
      {
        id: 'tp-clear',
        name: 'Se aleja',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/river-flowing.mp3',
        time: 1040,
        duration: 340,
        volume: 30,
        fadeIn: 60,
        fadeOut: 70,
        instruction: 'Se va. Lo que queda es agua corriendo',
        instructionDuration: 10,
        notes: '',
      },
      {
        id: 'tp-birds',
        name: 'Despues',
        kind: 'ambient',
        icon: 'forest',
        color: CUE_COLORS.earth,
        sound: 'ambient/forest-day.mp3',
        time: 1120,
        duration: 260,
        volume: 24,
        fadeIn: 50,
        fadeOut: 60,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'tp-drop',
        name: 'Gota',
        kind: 'fx',
        icon: 'rain',
        color: CUE_COLORS.tonal,
        sound: 'fx/water-drop.mp3',
        time: 1150,
        duration: 10,
        volume: 38,
        fadeIn: 0,
        fadeOut: 4,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'tp-end',
        name: 'Despejado',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.closing,
        sound: 'bells/singing-bell.mp3',
        time: 1380,
        duration: 60,
        volume: 54,
        fadeIn: 3,
        fadeOut: 30,
        instruction: 'Ha pasado. Abre los ojos',
        instructionDuration: 9,
        notes: '',
      },
    ],
  },
  {
    id: 'default-bajo-las-estrellas',
    name: 'Bajo las estrellas',
    createdAt: '2026-08-29T00:00:00.000Z',
    durationSeconds: 1080,
    cues: [
      {
        id: 'be-start',
        name: 'Sal fuera',
        kind: 'bowl',
        icon: 'bowl',
        color: CUE_COLORS.opening,
        sound: 'bells/crystal-bowl-medium.mp3',
        time: 0,
        duration: 30,
        volume: 54,
        fadeIn: 1,
        fadeOut: 15,
        instruction: 'Mira arriba. No busques nada',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'be-bed',
        name: 'Viento',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/wind-peaceful.mp3',
        time: 30,
        duration: 960,
        volume: 17,
        fadeIn: 50,
        fadeOut: 80,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'be-p1',
        name: 'Punto',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.tonal,
        sound: 'fx/crystal-tone.mp3',
        time: 180,
        duration: 20,
        volume: 38,
        fadeIn: 2,
        fadeOut: 10,
        instruction: 'Una estrella tarda en llegar hasta aqui',
        instructionDuration: 10,
        notes: '',
      },
      {
        id: 'be-cath',
        name: 'Fondo lejano',
        kind: 'ambient',
        icon: 'rain',
        color: CUE_COLORS.water,
        sound: 'ambient/cathedral-ambience.mp3',
        time: 300,
        duration: 300,
        volume: 10,
        fadeIn: 60,
        fadeOut: 90,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'be-owl',
        name: 'Buho',
        kind: 'ambient',
        icon: 'forest',
        color: CUE_COLORS.earth,
        sound: 'ambient/owl-distant.mp3',
        time: 420,
        duration: 60,
        volume: 20,
        fadeIn: 8,
        fadeOut: 20,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'be-p2',
        name: 'Silencio',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.tonal,
        sound: 'fx/gentle-tone.mp3',
        time: 600,
        duration: 20,
        volume: 36,
        fadeIn: 2,
        fadeOut: 10,
        instruction: 'El silencio de aqui no es el de dentro',
        instructionDuration: 10,
        notes: '',
      },
      {
        id: 'be-p3',
        name: 'Punto',
        kind: 'fx',
        icon: 'bell',
        color: CUE_COLORS.tonal,
        sound: 'fx/crystal-tone.mp3',
        time: 840,
        duration: 20,
        volume: 36,
        fadeIn: 2,
        fadeOut: 10,
        instruction: '',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'be-end',
        name: 'Vuelve',
        kind: 'bell',
        icon: 'bell',
        color: CUE_COLORS.closing,
        sound: 'bells/singing-bell.mp3',
        time: 1010,
        duration: 70,
        volume: 52,
        fadeIn: 4,
        fadeOut: 35,
        instruction: 'Entra cuando quieras',
        instructionDuration: 9,
        notes: '',
      },
    ],
  },
];
