// Single source of truth for a preset's session length: the stored
// durationSeconds, or — for presets saved before that field existed — the end
// of the last cue rounded up to a whole minute (minimum 60s).
export function presetDurationSeconds(preset) {
  if (typeof preset?.durationSeconds === 'number') return preset.durationSeconds;
  const lastCueEnd = (preset?.cues ?? []).reduce(
    (max, cue) => Math.max(max, cue.time + (cue.duration ?? 0)),
    0
  );
  return Math.max(60, Math.ceil(lastCueEnd / 60) * 60);
}

// Default presets are app content (translated by id); user presets show their
// literal name. t echoes the key back on miss, which is how we detect a user preset.
export function resolvePresetName(preset, t) {
  const key = `presets.${preset.id}`;
  const translated = t(key);
  return translated === key ? preset.name : translated;
}

export const DEFAULT_PRESETS = [
  {
    id: 'default-yoga-nidra',
    name: 'Yoga Nidra',
    createdAt: '2026-06-07T00:00:00.000Z',
    durationSeconds: 1800,
    cues: [
      {
        id: 'yn-start',
        name: 'Inicio',
        kind: 'bell',
        icon: 'bell',
        color: '#f6a133',
        sound: 'bells/singing-bell.mp3',
        time: 0,
        duration: 25,
        volume: 72,
        fadeIn: 1,
        fadeOut: 10,
        instruction: 'Acuéstate. Ojos cerrados. No te muevas',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'yn-ocean',
        name: 'Océano',
        kind: 'ambient',
        icon: 'rain',
        color: '#6fa7c4',
        sound: 'ambient/ocean-gentle.mp3',
        time: 60,
        duration: 1500,
        volume: 36,
        fadeIn: 30,
        fadeOut: 40,
        instruction: 'Escucha el sonido. No hagas nada',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'yn-breath',
        name: 'Respiración',
        kind: 'fx',
        icon: 'breath',
        color: '#a0c4e8',
        sound: 'fx/breath-cue.mp3',
        time: 180,
        duration: 20,
        volume: 55,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Observa el aire que entra y sale',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'yn-scan1',
        name: 'Cuerpo superior',
        kind: 'fx',
        icon: 'bell',
        color: '#e0c46f',
        sound: 'fx/gentle-tone.mp3',
        time: 360,
        duration: 15,
        volume: 52,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Mano derecha · brazo · hombro · cuello',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'yn-scan2',
        name: 'Torso',
        kind: 'fx',
        icon: 'bell',
        color: '#e0c46f',
        sound: 'fx/gentle-tone.mp3',
        time: 600,
        duration: 15,
        volume: 52,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Pecho · abdomen · espalda · cadera',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'yn-scan3',
        name: 'Cuerpo inferior',
        kind: 'fx',
        icon: 'bell',
        color: '#e0c46f',
        sound: 'fx/gentle-tone.mp3',
        time: 840,
        duration: 15,
        volume: 52,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Pierna derecha · izquierda · pies',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'yn-opposites',
        name: 'Pares opuestos',
        kind: 'fx',
        icon: 'bell',
        color: '#9bb56f',
        sound: 'fx/crystal-tone.mp3',
        time: 1020,
        duration: 20,
        volume: 50,
        fadeIn: 3,
        fadeOut: 6,
        instruction: 'Frío · calor · pesado · ligero · dolor · placer',
        instructionDuration: 9,
        notes: '',
      },
      {
        id: 'yn-visual',
        name: 'Visualización',
        kind: 'fx',
        icon: 'bell',
        color: '#b886d0',
        sound: 'fx/flute-peaceful.mp3',
        time: 1260,
        duration: 35,
        volume: 48,
        fadeIn: 6,
        fadeOut: 10,
        instruction: 'Un lago tranquilo al amanecer',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'yn-return',
        name: 'Retorno',
        kind: 'bell',
        icon: 'bell',
        color: '#c97761',
        sound: 'bells/chime-meditation.mp3',
        time: 1500,
        duration: 20,
        volume: 62,
        fadeIn: 2,
        fadeOut: 8,
        instruction: 'Vuelve a sentir tu cuerpo completo',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'yn-wake',
        name: 'Despertar',
        kind: 'bell',
        icon: 'bell',
        color: '#f6a133',
        sound: 'bells/meditation-bell-classic.mp3',
        time: 1680,
        duration: 22,
        volume: 70,
        fadeIn: 1,
        fadeOut: 8,
        instruction: 'Mueve los dedos. Respira profundo',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'yn-end',
        name: 'Cierre',
        kind: 'bowl',
        icon: 'bowl',
        color: '#b886d0',
        sound: 'bells/tibetan-bowl-resonant.mp3',
        time: 1770,
        duration: 120,
        volume: 80,
        fadeIn: 8,
        fadeOut: 22,
        instruction: '',
        instructionDuration: 5,
        notes: '',
      },
    ],
  },
  {
    id: 'default-pranayama-478',
    name: 'Pranayama 4-7-8',
    createdAt: '2026-06-07T00:00:00.000Z',
    durationSeconds: 900,
    cues: [
      {
        id: 'pr478-start',
        name: 'Inicio',
        kind: 'bell',
        icon: 'bell',
        color: '#f6a133',
        sound: 'bells/japanese-temple-bell.mp3',
        time: 0,
        duration: 20,
        volume: 76,
        fadeIn: 1,
        fadeOut: 6,
        instruction: 'Inhala 4 · Retén 7 · Exhala 8',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'pr478-r1',
        name: 'Ronda 1',
        kind: 'fx',
        icon: 'breath',
        color: '#a0c4e8',
        sound: 'fx/breath-cue.mp3',
        time: 120,
        duration: 30,
        volume: 60,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Inhala 4 · Retén 7 · Exhala 8',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'pr478-rest1',
        name: 'Descanso',
        kind: 'ambient',
        icon: 'rain',
        color: '#6fa7c4',
        sound: 'ambient/river-gentle.mp3',
        time: 300,
        duration: 60,
        volume: 42,
        fadeIn: 10,
        fadeOut: 10,
        instruction: 'Respira normal. Descansa',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'pr478-r2',
        name: 'Ronda 2',
        kind: 'fx',
        icon: 'breath',
        color: '#a0c4e8',
        sound: 'fx/breath-cue.mp3',
        time: 360,
        duration: 30,
        volume: 60,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Reanuda: Inhala 4 · Retén 7 · Exhala 8',
        instructionDuration: 8,
        notes: '',
      },
      {
        id: 'pr478-mid',
        name: 'Mitad',
        kind: 'bell',
        icon: 'bell',
        color: '#e0c46f',
        sound: 'fx/chimes-light.mp3',
        time: 450,
        duration: 15,
        volume: 58,
        fadeIn: 1,
        fadeOut: 4,
        instruction: 'Mitad de práctica',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'pr478-r3',
        name: 'Ronda 3',
        kind: 'fx',
        icon: 'breath',
        color: '#a0c4e8',
        sound: 'fx/breath-cue.mp3',
        time: 600,
        duration: 30,
        volume: 60,
        fadeIn: 2,
        fadeOut: 5,
        instruction: 'Última ronda',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'pr478-end',
        name: 'Cierre',
        kind: 'bowl',
        icon: 'bowl',
        color: '#b886d0',
        sound: 'bells/tibetan-bowl-pure.mp3',
        time: 840,
        duration: 30,
        volume: 78,
        fadeIn: 3,
        fadeOut: 12,
        instruction: 'Completa. Respira natural',
        instructionDuration: 7,
        notes: '',
      },
    ],
  },
  {
    id: 'default-meditacion-matutina',
    name: 'Meditacion matutina',
    createdAt: '2026-06-07T00:00:00.000Z',
    durationSeconds: 1200,
    cues: [
      {
        id: 'mm-start',
        name: 'Inicio',
        kind: 'bell',
        icon: 'bell',
        color: '#f6a133',
        sound: 'bells/meditation-bell.mp3',
        time: 0,
        duration: 18,
        volume: 76,
        fadeIn: 1,
        fadeOut: 7,
        instruction: 'Siéntate. Cierra los ojos',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'mm-ambient',
        name: 'Bosque',
        kind: 'ambient',
        icon: 'forest',
        color: '#9bb56f',
        sound: 'ambient/forest-day.mp3',
        time: 60,
        duration: 600,
        volume: 46,
        fadeIn: 20,
        fadeOut: 25,
        instruction: 'Observa tu respiración',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'mm-mid',
        name: 'Mitad',
        kind: 'bell',
        icon: 'bell',
        color: '#e0c46f',
        sound: 'bells/chime-meditation.mp3',
        time: 600,
        duration: 20,
        volume: 62,
        fadeIn: 1,
        fadeOut: 6,
        instruction: 'Mitad de la práctica',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'mm-final5',
        name: 'Últimos 5 min',
        kind: 'bell',
        icon: 'bell',
        color: '#c97761',
        sound: 'fx/chimes-medium.mp3',
        time: 900,
        duration: 18,
        volume: 60,
        fadeIn: 1,
        fadeOut: 5,
        instruction: 'Últimos 5 minutos',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'mm-return',
        name: 'Vuelve',
        kind: 'bell',
        icon: 'bell',
        color: '#b886d0',
        sound: 'bells/crystal-bowl-medium.mp3',
        time: 1140,
        duration: 25,
        volume: 70,
        fadeIn: 2,
        fadeOut: 10,
        instruction: 'Prepárate para volver',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'mm-end',
        name: 'Cierre',
        kind: 'bowl',
        icon: 'bowl',
        color: '#b886d0',
        sound: 'bells/tibetan-bowl-resonant.mp3',
        time: 1185,
        duration: 120,
        volume: 82,
        fadeIn: 8,
        fadeOut: 20,
        instruction: 'Abre los ojos cuando quieras',
        instructionDuration: 7,
        notes: '',
      },
    ],
  },
  {
    id: 'default-relajacion-profunda',
    name: 'Relajacion profunda',
    createdAt: '2026-06-07T00:00:00.000Z',
    durationSeconds: 1800,
    cues: [
      {
        id: 'rp-start',
        name: 'Inicio',
        kind: 'bell',
        icon: 'bell',
        color: '#f6a133',
        sound: 'bells/singing-bell.mp3',
        time: 0,
        duration: 22,
        volume: 72,
        fadeIn: 1,
        fadeOut: 8,
        instruction: 'Acuéstate. Cierra los ojos',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'rp-ocean',
        name: 'Océano',
        kind: 'ambient',
        icon: 'rain',
        color: '#6fa7c4',
        sound: 'ambient/ocean-gentle.mp3',
        time: 120,
        duration: 900,
        volume: 44,
        fadeIn: 25,
        fadeOut: 30,
        instruction: 'Deja que el cuerpo se hunda',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'rp-relax1',
        name: 'Suelta',
        kind: 'fx',
        icon: 'bell',
        color: '#e0c46f',
        sound: 'fx/flute-peaceful.mp3',
        time: 600,
        duration: 40,
        volume: 55,
        fadeIn: 5,
        fadeOut: 10,
        instruction: 'Relaja mandíbula, cuello, hombros',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'rp-deep',
        name: 'Profundo',
        kind: 'fx',
        icon: 'bell',
        color: '#9bb56f',
        sound: 'fx/crystal-tone.mp3',
        time: 1080,
        duration: 30,
        volume: 58,
        fadeIn: 3,
        fadeOut: 8,
        instruction: 'Más profundo',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'rp-return',
        name: 'Vuelve',
        kind: 'fx',
        icon: 'bell',
        color: '#c97761',
        sound: 'fx/water-drop.mp3',
        time: 1500,
        duration: 12,
        volume: 64,
        fadeIn: 1,
        fadeOut: 3,
        instruction: 'Empieza a volver',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'rp-wake',
        name: 'Despierta',
        kind: 'bell',
        icon: 'bell',
        color: '#b886d0',
        sound: 'bells/meditation-bell-classic.mp3',
        time: 1740,
        duration: 22,
        volume: 74,
        fadeIn: 1,
        fadeOut: 8,
        instruction: 'Mueve los dedos. Abre los ojos',
        instructionDuration: 7,
        notes: '',
      },
      {
        id: 'rp-end',
        name: 'Cierre',
        kind: 'gong',
        icon: 'gong',
        color: '#c97761',
        sound: 'bells/zen-gong.mp3',
        time: 1785,
        duration: 90,
        volume: 80,
        fadeIn: 4,
        fadeOut: 22,
        instruction: '',
        instructionDuration: 5,
        notes: '',
      },
    ],
  },
  {
    id: 'default-caminata-consciente',
    name: 'Caminata consciente',
    createdAt: '2026-06-07T00:00:00.000Z',
    durationSeconds: 600,
    cues: [
      {
        id: 'cc-start',
        name: 'Comienza',
        kind: 'fx',
        icon: 'bell',
        color: '#9bb56f',
        sound: 'fx/bird-chirp-multiple.mp3',
        time: 0,
        duration: 12,
        volume: 70,
        fadeIn: 1,
        fadeOut: 3,
        instruction: 'Empieza a caminar despacio',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'cc-paso',
        name: 'Pasos',
        kind: 'ambient',
        icon: 'forest',
        color: '#9bb56f',
        sound: 'ambient/crickets-gentle.mp3',
        time: 120,
        duration: 180,
        volume: 40,
        fadeIn: 12,
        fadeOut: 12,
        instruction: 'Siente cada paso',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'cc-escucha',
        name: 'Escucha',
        kind: 'fx',
        icon: 'bell',
        color: '#e0c46f',
        sound: 'fx/chimes-small.mp3',
        time: 240,
        duration: 14,
        volume: 62,
        fadeIn: 1,
        fadeOut: 4,
        instruction: '¿Qué escuchas?',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'cc-cuerpo',
        name: 'Cuerpo',
        kind: 'ambient',
        icon: 'forest',
        color: '#6fa7c4',
        sound: 'ambient/wind-gentle.mp3',
        time: 360,
        duration: 120,
        volume: 38,
        fadeIn: 10,
        fadeOut: 10,
        instruction: '¿Qué sientes en el cuerpo?',
        instructionDuration: 6,
        notes: '',
      },
      {
        id: 'cc-ritmo',
        name: 'Ritmo',
        kind: 'fx',
        icon: 'bell',
        color: '#9bb56f',
        sound: 'fx/bird-chirp-multiple.mp3',
        time: 480,
        duration: 12,
        volume: 65,
        fadeIn: 1,
        fadeOut: 3,
        instruction: 'Vuelve al ritmo del paso',
        instructionDuration: 5,
        notes: '',
      },
      {
        id: 'cc-end',
        name: 'Detente',
        kind: 'bell',
        icon: 'bell',
        color: '#f6a133',
        sound: 'bells/gong-bell.mp3',
        time: 570,
        duration: 25,
        volume: 74,
        fadeIn: 2,
        fadeOut: 10,
        instruction: 'Detente. Respira',
        instructionDuration: 7,
        notes: '',
      },
    ],
  },
];
